const val RELEASE_USER = "hendraanggrian"
const val RELEASE_REPO = "bundler"
const val RELEASE_GROUP = "com.$RELEASE_USER.$RELEASE_REPO"
const val RELEASE_ARTIFACT = "bundler"
const val RELEASE_VERSION = "0.3-rc1"
const val RELEASE_DESC = "Android extra field binder with annotation processor"
const val RELEASE_WEB = "https://github.com/$RELEASE_USER/$RELEASE_ARTIFACT"
